version: '3.4'

services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:     
      - pg
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file: .env

  pg:
    image: postgres:12.3-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
