default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: dev_articles_api_development

test:
  <<: *default
  database: dev_articles_api_test

production:
  <<: *default
  database: dev_articles_api_production
