default: &default
  adapter: postgresql
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: dev_articles_api_development

test:
  <<: *default
  database: dev_articles_api_test

production:
  <<: *default
  database: dev_articles_api_production
